### ISSUE TITLE
Doesn't compile on recent versions

### ISSUE THREAD

**Issue by chralg** [xreef/Aurora_Web_Invert_Monitor#1]
Hi,

First of all, thank you for your contribution to Aurora and the open source community!
I am using the ABB inverter together with a wind mill, but it functions in a similar way.

I am seeing difficulties in compiling the ide sketch. I can't seem to understand why the compiler is yelling about LastDataState beeing undeclared. I have attached the output.

`Compilation error: 'LastDataState' does not name a type`

[compile-output.txt](https://github.com/xreef/Aurora_Web_Invert_Monitor/files/10780694/compile-output.txt)

Thanks
Christofer

**Comment by xreef** [comment]
Hi,
you can find the compiling process here 
https://www.mischianti.org/2021/01/24/abb-aurora-web-inverter-monitor-wim-upload-the-sketch-and-front-end-9/
Bye Renzo

**Comment by chralg** [comment]
Hi again,

Thanks for helping,
I followed the process in the link before posting. As I am no c++ developer I have no clue, but is this really a library thing?
I am building the sketch on a Mac.  

Thanks
Christofer

**Comment by xreef** [comment]
Hi,
you must use 2.4.2 core and these libraries version.

esp8266/hardware/esp8266/2.4.2/cores/esp8266
esp8266/hardware/esp8266/2.4.2/variants/d1_mini

libraries/ArduinoJson/6.5.0-beta
libraries/ArduinoThread
esp8266/hardware/esp8266/2.4.2/libraries/DNSServer
libraries/EMailSender
esp8266/2.4.2/libraries/ESP8266WebServer
esp8266/hardware/esp8266/2.4.2/libraries/ESP8266WiFi
esp8266/2.4.2/libraries/ESP8266mDNS
esp8266/hardware/esp8266/2.4.2/libraries/Hash
libraries/NTPClient/3.2.1
esp8266/hardware/esp8266/2.4.2/libraries/SD
esp8266/hardware/esp8266/2.4.2/libraries/SPI
libraries/Thread/0.0.2
TimeLib
Timezone
libraries/Timezone/1.2.4
libraries/WebSockets/2.3.5
WiFiManager
esp8266/hardware/esp8266/2.4.2/libraries/Wire
aurora_communication_protocol

bye Renzo

**Comment by nobodyman1** [comment]
> Hi,
> 
> First of all, thank you for your contribution to Aurora and the open source community! I am using the ABB inverter together with a wind mill, but it functions in a similar way.
> 
> I am seeing difficulties in compiling the ide sketch. I can't seem to understand why the compiler is yelling about LastDataState beeing undeclared. I have attached the output.
> 
> `Compilation error: 'LastDataState' does not name a type`
> 
> [compile-output.txt](https://github.com/xreef/Aurora_Web_Invert_Monitor/files/10780694/compile-output.txt)
> 
> Thanks Christofer

It´s quite easy to fix:
Change `LastDataState manageLastDataState(...)` to `struct LastDataState manageLastDataState(...)`.
