### ISSUE TITLE
Upload on ESP8266 Problem

### ISSUE THREAD

**Issue by jgrabitzky** [xreef/Aurora_Web_Invert_Monitor#2]
Hello

First of all, thank you for the code.

Unfortunately I cannot load the files onto my ESP.

I run this:

esptool.py --port /dev/cu.usbserial-14440 write_flash -fm dio 0x00000 Aurora_Web_Inverter_Monitor.d1_mini.bin

esptool.py v4.7.0
Serial port /dev/cu.usbserial-14440
Connect....
Detecting chip type... Unsupported detection protocol, switch and try again...
Connect....
Chip type is recognized... ESP8266
Chip is ESP8266EX
Features: WiFi
Quartz is 26 MHz
MAC: 40:91:51:45:6b:52
Uploading stub...
Running stub...
Stub is running...
Configure flash size...
Flash is cleared from 0x00000000 to 0x00075fff...
Compressed 481104 bytes to 332882...
Wrote 481104 bytes (332882 compressed) at 0x00000000 in 32.2 seconds (effective 119.4 kbit/s)...
Hash of the verified data.

Leave...
Hard reset via RTS pin...
 esptool.py --port /dev/cu.usbserial-14440 write_flash -fm dio 0x10000 Aurora_Web_Inverter_Monitor.spiffs.bin

esptool.py v4.7.0
Serial port /dev/cu.usbserial-14440
Connect............
Detecting chip type... Unsupported detection protocol, switch and try again...
Connect....
Chip type is recognized... ESP8266
Chip is ESP8266EX
Features: WiFi
Quartz is 26 MHz
MAC: 40:91:51:45:6b:52
Uploading stub...
Running stub...
Stub is running...
Configure flash size...
Flash is cleared from 0x00010000 to 0x0020afff...
Compressed 2076672 bytes to 1150302...
Wrote 2076672 bytes (1150302 compressed) at 0x00010000 in 111.1 seconds (effective 149.6 kbit/s)...
Hash of the verified data.

Leave...
Hard reset via RTS pin...

After that I reset the ESP but didn't get WIFI AP.

When I upload the firmware and restart it, I get an AP and can also integrate it into my network.

If I use the FTP firmware I get:
Connect to 192.168.112.80:21...
Status: Connection attempt failed with “ECONNREFUSED – Connection denied by server”.
Error: Failed to connect to server

I would be grateful for help

**Comment by Ichsannnzz** [comment]
how to fix it???

**Comment by xreef** [comment]
Hi Ichsannnzz,
I don't know; there is probably a problem with the module. I tested this procedure, and it works correctly.
https://mischianti.org/abb-aurora-web-inverter-monitor-wim-upload-the-sketch-and-front-end-9/
Bye Renzo
